Ambrose:-sighs-"Another uneventful day........"
Ambrose:"I wonder........"
Ambrose:"..........."
Ambrose:"........"
Ambrose:"I really shouldn't, but...."
Ambrose:"I want to see what the city is like......"
Ambrose:"I've never even stepped inside once. All I can see is the skyline, its unnatural lights, and the loud noises....."
Ambrose:"........Humans can be very rash though....."
Ambrose:"They keep yelling at me every time I try to get inside that place......."
Ambrose:"They also call me a monster, and point their weapons at me........."
Ambrose:"Am I really a monster? Or are they just scared?"
Ambrose:"Looks like I'll never find out......"